// <auto-generated />
namespace Company.DIV.ConfigMgr.Data.Read.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemoveNavProp_Config_JConfigPlans : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveNavProp_Config_JConfigPlans));
        
        string IMigrationMetadata.Id
        {
            get { return "201702020559010_RemoveNavProp_Config_JConfigPlans"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
