// <auto-generated />
namespace Company.DIV.ConfigMgr.Data.Read.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClassInsteadOfInterface4EntityBaseTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClassInsteadOfInterface4EntityBaseTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201701110252225_ClassInsteadOfInterface4EntityBaseTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
