// <auto-generated />
namespace Company.DIV.ConfigMgr.DataRead.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PreCQRS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PreCQRS));
        
        string IMigrationMetadata.Id
        {
            get { return "201701022117030_PreCQRS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
